In [1]:
import pandas as pd

In [2]:
arquivo = "censo_educacao.xlsx"

In [3]:
df = pd.read_excel(arquivo)
df

                    NMU   ANO   SIFI  FCMI  MCSI  SUPCOM  INSND
0       Abadia de Goiás  2010   3234  1139  1103     328      0
1             Abadiânia  2010   7968  2335  2626     474     88
2               Acreúna  2010  10872  2421  3072     696     67
3             Adelândia  2010   1307   343   434      65      0
4    Água Fria de Goiás  2010   2798   611   727      97      6
..                  ...   ...    ...   ...   ...     ...    ...
241              Varjão  2010   2048   549   486      98      3
242          Vianópolis  2010   6253  1930  2020     480     72
243      Vicentinópolis  2010   3934   936  1021     283     18
244            Vila Boa  2010   2335   600   724      80     69
245       Vila Propício  2010   2938   873   377      87     22

[246 rows x 7 columns]

In [5]:
df.to_csv("educacao.csv", index=False) # salva o dataframe modificado